name: 🦺 Type checkers tests

concurrency:
  group: type-checkers-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - "strawberry/**"
      - "tests/mypy/**"
      - "tests/pyright/**"
      - "pyproject.toml"
      - "poetry.lock"
      - ".github/workflows/test-type-checkers.yml"

jobs:
  mypy:
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    name: Mypy on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: pip install tox tox-factor
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "tox.ini"

      - name: tox
        run: |
          export TOX_INTERPRETER=$(sed "s/\([0-9]*\)\.\([0-9]*\).*/py\1\2/g" <<<"${{ matrix.python-version }}")
          tox -f mypy-$TOX_INTERPRETER


  pyright:
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    name: Pyright on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: pip install tox tox-factor
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "tox.ini"

      - uses: actions/setup-node@v2
      - run: npm install -g --no-package-lock --no-save pyright

      - name: tox
        run: |
          export TOX_INTERPRETER=$(sed "s/\([0-9]*\)\.\([0-9]*\).*/py\1\2/g" <<<"${{ matrix.python-version }}")
          tox -f pyright-$TOX_INTERPRETER
